# Generated by Django 4.2.2 on 2023-06-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afastamento',
            name='motivo',
            field=models.CharField(choices=[('fl', 'Folga'), ('fr', 'Ferias'), ('lp', 'Licença Premio'), ('lm', 'Licença medica'), ('em', 'Cedido')], max_length=10),
        ),
    ]
