# Generated by Django 4.2.2 on 2023-06-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sefit', '0002_alter_afastamento_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afastamento',
            name='obs',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
